[build]
  command = "pip install -r requirements.txt"
  publish = "public"  # (You can leave this as an empty folder if your site is fully dynamic)
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/wsgi_handler"
  status = 200
